### ISSUE TITLE
Use loops

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/pyca-ansible#1]
Instead of copying tasks, you can just loop over tasks with different items.
Example:

```yml
  - name: Ensure the PyCA services are started and enabled
    ansible.builtin.systemd:
      name: '{{ item }}.service'
      enabled: true
      state: started
    loop:
      - pyca
      - pyca-ui
```
